### ISSUE TITLE
Fork me on Github banner too big

### ISSUE THREAD

**Issue by abrahimladha** [maximecb/Turing-Drawings#4]
On my phone, it makes the num symbols field unclickable. On desktop, half the num symbols field is unclickable.

**Comment by inexist3nce** [comment]
any screen smaller than 1100px wide should conflict with the forkme image

**Comment by maximecb** [comment]
Found a potential solution here: https://codepo8.github.io/css-fork-on-github-ribbon/

**Comment by maximecb** [comment]
I took some inspiration from that solution and used CSS to just hide the banner when the screen is too small.
